name: Test

on:
  push: 
    branches:
      - '*' 
  pull_request:
    branches:
      - '*' 

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Listar variáveis de ambiente
        run: env

      - name: Testar variável
        run: echo $RODRIGO
